[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.13"

[rpc_endpoints]
anvil = "http://localhost:8545/"
goerli = "https://ethereum-goerli-rpc.allthatnode.com"
sepolia = "https://ethereum-sepolia-rpc.allthatnode.com"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arbitrum.public-rpc.com"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config